spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select *
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select *
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  thymeleaf:
    cache: false

server:
  port: 8080
logging:
  level:
    org.mybatis: debug
    org.springframework.security: debug

flyway:
  locations: classpath:db/migration
  enabled: true
  baseline-on-migrate: true




